neo_mecanum_node:
  ros__parameters:
    #robot's geometric parameters:

    #Diameter of std. mecanum wheel
    wheelDiameter: 0.08
    #Length of the mobile robot from wheel center to wheel center
    robotLength: 0.3
    #Width from wheel center to wheel center
    robotWidth: 0.3
    #stddev vel x
    devX: 0.2
    #stddev vel y
    devY: 0.2
    #stddev vel z
    devZ: 0.2
    #stddev vel roll
    devRoll: 0.2
    #stddev vel pitch
    devPitch: 0.2
    #stddev vel x yaw
    devYaw: 0.2
    sendTransform: true
