game_controller_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.15
    autorepeat_rate: 125.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
      y: 0
    scale_linear:
      x: 0.2
      y: 0.2
    scale_linear_turbo:
      x: 0.4
      y: 0.4

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.2
    scale_angular_turbo:
      yaw: 0.4

    enable_button: 9
    enable_turbo_button: 10
    require_enable_button: true
