# Launch configuration parameters (to control which components to launch)
launch_config:
  # Control Computer nodes
  use_joy: false           # Set to true to launch joystick control
  use_slam: false          # Set to true to launch SLAM Toolbox
  use_rviz: true          # Set to true to launch RViz for visualization
  use_robot_state: true  # Set to true to launch robot state publisher
  use_xbox: true          # Set to true to launch Xbox controller


  # Control RPi nodes
  use_inv_kin: true       # Set to true to launch inv_kin_node
  use_odom: true          # Set to true to launch odom_node
  use_rplidar: true       # Set to true to launch rplidar_node
  use_serial_talker: true # Set to true to launch serial talker
  use_x_serial: false      # Set to true to launch x_serial
  use_slam_pi: true          # Set to true to launch SLAM Toolbox
