slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    use_map_saver: true
    mode: mapping
    map_update_interval: 3.0
    resolution: 0.05
    max_laser_range: 10.0
    transform_publish_period: 0.02
    tf_buffer_duration: 30.0
    use_scan_matching: true
    minimum_travel_distance: 0.15
    minimum_travel_heading: 0.25
    scan_buffer_size: 10
    do_loop_closing: true
    loop_search_maximum_distance: 3.0
    loop_match_minimum_response_fine: 0.45
    use_scan_barycenter: true
    reverse_scan: false
    multi_thread_map_update: true
