# RPLIDAR Configuration Parameters:
#
# channel_type:
#   - Defines the communication channel for the LIDAR.
#   - Options: "serial", "tcp".
#   - Use "serial" for USB communication and "tcp" for network-based communication.
#
# serial_port:
#   - Specifies the serial port to which the RPLIDAR is connected.
#   - Example: "/dev/ttyUSB0" for a common USB port on Linux systems.
#
# serial_baudrate:
#   - Sets the baud rate for the serial communication.
#   - Common value: "115200" for RPLIDAR A2M8.
#
# frame_id:
#   - The reference frame in which LIDAR data is published.
#   - Example: "laser_frame" or "base_link" (depending on the robot setup).
#
# inverted:
#   - Indicates whether to invert the LIDAR scan data.
#   - Useful when the LIDAR is mounted upside-down.
#   - Options: "true", "false".
#
# angle_compensate:
#   - Enables or disables angle compensation for the scan data.
#   - It helps to smoothen scan angles when the LIDAR is moving.
#   - Options: "true", "false".
#
# RPLIDAR Scan Modes:
# 
# 1. Standard Mode:
#    - Default mode, balanced speed and accuracy.
#    - Typically scans at around 2k points per second.
#    - Best for general use with moderate speed and resolution.
#
# 2. Express Mode:
#    - Increases scan rate to around 4k points per second.
#    - Prioritizes speed over accuracy.
#    - Suitable for environments with fast-moving objects or when quicker updates are needed.
#
# 3. Boost Mode:
#    - Highest performance mode, scans at around 8k points per second.
#    - Focuses on real-time data at the expense of some accuracy.
#    - Ideal for high-speed applications requiring rapid updates.

rplidar_node:
  ros__parameters:
    channel_type: "serial"         # Communication type: serial or tcp
    serial_port: "/dev/ttyUSB0"    # Serial port where the RPLIDAR is connected
    serial_baudrate: 115200        # A2M8 baudrate
    frame_id: "laser_frame"        # Reference frame for the LIDAR
    inverted: false                # Whether to invert the LIDAR scan
    angle_compensate: true         # Angle compensation for scan data
    scan_mode: "Standard"          # Options: "Standard", "Express", "Boost"